### PR TITLE
Lesson 1-3

### PR DESCRIPTION
**Pull request by AnnaSolovykh**
Here is the third home task.

### CODE REVIEW

**Comment by Jkuffler** [comment]
This is great! I like how you've used `console.log(event)` because while you're learning this material it's nice to see the big picture as to what methods are available on an event (when you click it in the browser's console). One thing to point out for the future: the form should be adding items to the list so that the new to-dos include the same styling as the rest of the list of to-dos

**Comment by AnnaSolovykh** [comment]
Thank you! 
I agree that list items should look the same, so I have fixed the styling but had to change the code architecture a bit for that... Now it is not exactly as it should be according to the task. Is it ok? :)
I have sent {newToDo} to the component where <ul> is located.

**Comment by AnnaSolovykh** [comment]
Sorry for asking, I am working on the theory and have learnt about controlled components. Shall I pass toDo also as a prop to add value={toDo} to the input element?

**Comment by AnnaSolovykh** [comment]
Sorry for asking, I am working on the theory and have learnt about controlled components. Shall I pass newToDo also as a prop to add value={newToDo} to the input element?

**Pull request merged**
