### PR TITLE
Lesson 1-1

### PR DESCRIPTION
**Pull request by AnnaSolovykh**
Week-1 Assignment

### CODE REVIEW

**Comment by Jkuffler** [comment]
Almost got this :) The return values for your App.jsx are throwing an error that points to the line after you've mapped over the array. The extra closing </li> tag can be deleted to render the list. Notice the bullet points do not respond to styling - consider changing list style type as well perhaps.

**Comment by AnnaSolovykh** [comment]
> Almost got this :) The return values for your App.jsx are throwing an error that points to the line after you've mapped over the array. The extra closing tag can be deleted to render the list. Notice the bullet points do not respond to styling - consider changing list style type as well perhaps.

Thank you for the review! Sorry what kind of error are you talking about? I don't see any either in the terminal or in the console. 
Снимок экрана 2023-03-14 в 10 16 56
Снимок экрана 2023-03-14 в 10 16 43

As for the list styling, terminal throws an error if I style it prettier. How can this be fixed?
Снимок экрана 2023-03-14 в 10 20 29

Thank you in advance!

**Comment by AnnaSolovykh** [comment]
I still don't get it about the error, sorry :(
But I have added the brackets and made the list look fancier.

Снимок экрана 2023-03-14 в 14 36 19

**Comment by Jkuffler** [comment]
That's a small error on my part. I had accidentally attempted to render code that had been removed. I fixed what I was pulling into my editor and it works great. Good use of flex! You could also remove the bullet points altogether was another idea that had crossed my mind. Great work! Apologies for small confusion.

**Comment by AnnaSolovykh** [comment]
Great, thank you a lot for your review!

**Pull request merged**
